<?php

return [
    'admins'=>'مشاهدة المشرفين',
    'admins.create'=>'انشاء مشرف جديد',
    'admins.edit'=>'تعديل على مشرف',
    'admins.destroy'=>'حذف مشرف',
    'attributes'=>'مشاهدة صفات المنتجات',
    'attributes.create'=>'انشاء صفات منتج جديده',
    'attributes.edit'=>'تعديل على صفات منتج',
    'attributes.destroy'=>'حذف صفات منتج',
    'brands'=>'مشاهدة الماركات ',
    'brands.create'=>'انشاء ماركه جديده',
    'brands.edit'=>'تعديل على ماركه',
    'brands.destroy'=>'حذف ماركه ',
    'categories'=>'مشاهدة الاقسام',
    'categories.create'=>'انشاء قسم جديد',
    'categories.edit'=>'تعديل على قسم',
    'categories.destroy'=>'حذف قسم',
    'delivery'=>'مشاهدة سعر التوصيل بالنسبه للمدن',
    'delivery.create'=>'انشاء سعر توصيل جديد',
    'delivery.edit'=>'تعديل على سعر توصيل',
    'delivery.destroy'=>'حذف سعر توصيل',
    'options'=>'مشاهدة خصائص صفات المنتجات',
    'options.create'=>'انشاء خصائص صفات منتج جديده',
    'options.edit'=>'تعديل على خصائص صفات منتج',
    'options.destroy'=>'حذف خصائص صفات منتج',
    'products'=>'مشاهدة المنتجات',
    'products.create'=>'انشاء منتج جديد',
    'products.edit'=>'تعديل على  منتج',
    'products.destroy'=>'حذف منتج',
    'roles'=>'مشاهدة الاوامر والصلاحيات',
    'roles.create'=>'انشاء اوامر وصلاحيات جديده',
    'roles.edit'=>' تعديل الاوامر والصلاحيات',
    'roles.destroy'=>'حذف الاوامر والصلاحيات',
    'settings.edit'=>' تعديل الاعدادات',
    'vendors'=>'مشاهدة البائعين واسعار شحنهم',
    'vendors.create'=>'انشاء بائع وسعر شحن جديد',
    'vendors.edit'=>' تعديل على بائعين',
    'vendors.destroy'=>'حذف بائعين',
    'contactus'=>'مشاهدة رسائل الزوار او المستخدمين',
    'contactus.destroy'=>'حذف رسائل المستخدمين او الزوار',
    
]


?>
